// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1, arg2) {
  return window['go']['main']['App']['AddCategory'](arg1, arg2);
}

export function AddCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateDoc(arg1, arg2) {
  return window['go']['main']['App']['CreateDoc'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteCommand(arg1, arg2) {
  return window['go']['main']['App']['DeleteCommand'](arg1, arg2);
}

export function DeleteDoc(arg1) {
  return window['go']['main']['App']['DeleteDoc'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetDocCategories() {
  return window['go']['main']['App']['GetDocCategories']();
}

export function GetDocContent(arg1) {
  return window['go']['main']['App']['GetDocContent'](arg1);
}

export function GetDocs(arg1) {
  return window['go']['main']['App']['GetDocs'](arg1);
}

export function SaveDocContent(arg1, arg2) {
  return window['go']['main']['App']['SaveDocContent'](arg1, arg2);
}

export function UpdateCommand(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateCommand'](arg1, arg2, arg3, arg4, arg5, arg6);
}
