// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCategory(arg1:string,arg2:string):Promise<void>;

export function AddCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function CreateDoc(arg1:string,arg2:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteCommand(arg1:string,arg2:string):Promise<void>;

export function DeleteDoc(arg1:string):Promise<void>;

export function GetCategories():Promise<Array<Record<string, any>>>;

export function GetCommands():Promise<Array<main.CommandInfo>>;

export function GetDocCategories():Promise<Array<main.DocCategory>>;

export function GetDocContent(arg1:string):Promise<string>;

export function GetDocs(arg1:string):Promise<Array<main.DocFile>>;

export function SaveDocContent(arg1:string,arg2:string):Promise<void>;

export function UpdateCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;
